//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreetWatch.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ДеталиРезультата
    {
        public Nullable<int> IDФото { get; set; }
        public int IDДетали { get; set; }
        public Nullable<int> IDЗаказа { get; set; }
        public Nullable<int> IDПользователя { get; set; }
        public string КомментКФотке { get; set; }
    
        public virtual Фото Фото { get; set; }
        public virtual Результат Результат { get; set; }
    }
}
