//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreetWatch.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Исполнение_заказа
    {
        public int IDЗаказа { get; set; }
        public int IDИсполнителя { get; set; }
        public Nullable<int> СделаноНесделано { get; set; }
        public Nullable<System.DateTime> Времяподтверждения { get; set; }
        public Nullable<System.DateTime> ДатавремяИсполнения { get; set; }
    
        public virtual Заказ Заказ { get; set; }
        public virtual Исполнитель Исполнитель { get; set; }
        public virtual Результат Результат { get; set; }
    }
}
