//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreetWatch.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователь
    {
        public Пользователь()
        {
            this.СессияПользователя = new HashSet<СессияПользователя>();
        }
    
        public int IDПользователя { get; set; }
        public string Почта { get; set; }
        public string ХэшПароля { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Обращение { get; set; }
    
        public virtual Заказчик Заказчик { get; set; }
        public virtual Исполнитель Исполнитель { get; set; }
        public virtual ICollection<СессияПользователя> СессияПользователя { get; set; }
    }
}
